[package]
name = "s3sync"
version = "0.1.0"
edition = "2021"

[dependencies]
object_store = { version = "~0.10", features = ["aws"] } 
tokio = { version = "1", features = ["full"] }
futures = "~0"
clap = { version = "^4.5", features = ["derive"] }
env_logger = "~0.11"
log = "0"
